include: always install all files
Depending on meson options, yaml or editline support may or may not be
compiled. However, ecoli.h always includes ecoli_editline.h and
ecoli_yaml.h, regardless of build options.

When yaml is disable (for example), it causes an error when including
ecoli.h:

/usr/include/ecoli.h:64:10: fatal error: ecoli_yaml.h: No such file or directory
   64 | #include <ecoli_yaml.h>
      |          ^~~~~~~~~~~~~~

Instead of resorting to obscure build-time generate config.h, always
install all headers. There will be a link-time error if unavailable
symbols are used anyway.

Fixes: 8c4e1f8c65eb ("meson: revamp options")
Signed-off-by: Robin Jarry <robin@jarry.cc>