node_file: fix -Werror=discarded-qualifiers with glibc 2.42.9000
Glibc 2.42 introduced const-correct overloads for string functions like
strchr(), strrchr(), strstr(), etc.

This causes a warning on build:

src/node_file.c: In function ‘split_path’:
src/node_file.c:78:20: error: assignment discards ‘const’ qualifier from
pointer target type [-Werror=discarded-qualifiers]
   78 |         last_slash = strrchr(path, '/');
      |                    ^

Change the variable type to const. We don't need to modify it anyway.

Link: https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=cd748a63ab1a
Signed-off-by: Robin Jarry <rjarry@redhat.com>