examples: fix compilation warning
count missing initialization due to the `goto fail`

fix error/warning:
../examples/readline/main.c: In function ‘show_help’:
../examples/readline/main.c:143:16: error: ‘count’ may be used
uninitialized [-Werror=maybe-uninitialized]
  143 |         size_t count;
      |                ^~~~~

Signed-off-by: Vincent Jardin <vjardin@free.fr>