interact: remove leftover include
Fix an error when building without editline support:

../src/interact.c:12:10: fatal error: histedit.h: No such file or directory
   12 | #include <histedit.h>
      |          ^~~~~~~~~~~~
compilation terminated.

Fixes: bc90312a4285 ("editline: split in 2 files")
Signed-off-by: Robin Jarry <rjarry@redhat.com>
Reviewed-by: Olivier Matz <zer0@droids-corp.org>