yaml: fix build error
Fix the following build error:

../src/yaml.c: In function ‘export_ec_node’:
../src/yaml.c:741:43: error: ‘EC_EDITLINE_HELP_ATTR’ undeclared (first use in this function)
  741 |                 help = ec_dict_get(attrs, EC_EDITLINE_HELP_ATTR);
      |                                           ^~~~~~~~~~~~~~~~~~~~~

Some EC_EDITLINE_* and ec_editline_* symbols were renamed to use
a generic ec_interact_ prefix.

Fixes: bc90312a4285 ("editline: split in 2 files")
Signed-off-by: Robin Jarry <rjarry@redhat.com>
Reviewed-by: Olivier Matz <zer0@droids-corp.org>