tests: fix error when building without yaml
Fix the following error when libyaml support isn't enabled:

/usr/bin/ld: test/yaml.p/yaml.c.o: in function `main':
test/yaml.c:59:(.text.startup+0xeb): undefined reference to `ec_yaml_export'
/usr/bin/ld: test/yaml.c:69:(.text.startup+0x103): undefined reference to `ec_yaml_import'
/usr/bin/ld: test/yaml.c:110:(.text.startup+0x278): undefined reference to `ec_yaml_export'
collect2: error: ld returned 1 exit status

Fixes: dedee94e330e ("yaml: add ec_yaml_export function")
Signed-off-by: Robin Jarry <rjarry@redhat.com>
Reviewed-by: Olivier Matz <zer0@droids-corp.org>