sh_lex: fix maybe-uninitialized error
Fix the following error:

src/ecoli_strvec.c: In function ‘ec_strvec_sh_lex_str’:
src/ecoli_strvec.c:497:13: error: ‘arg_start’ may be used uninitialized [-Werror=maybe-uninitialized]
  497 |         if (sh_lex_set_attrs(strvec, ec_strvec_len(strvec) - 1,
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  498 |                              arg_start, i) < 0)
      |                              ~~~~~~~~~~~~~

Fixes: b59abaca7cff ("sh_lex: store metadata about token positions in original string")
Signed-off-by: Robin Jarry <rjarry@redhat.com>